{
  # Import all your configuration modules here
  imports = [
    ./options.nix
    ./keymaps.nix
    ./completion.nix
    ./bufferline.nix
    ./ledger.nix
    ./oil.nix
    ./telescope.nix
    ./lsp.nix
    ./colorscheme.nix
    ./statusline.nix
    ./treesitter.nix
    ./indent-blankline.nix
    ./gitsigns.nix
    ./rainbow-delimiters.nix
    ./autopairs.nix
    ./which-key.nix
    ./trouble.nix
    ./fidget.nix
    ./persistence.nix
    ./neogit.nix
    ./lazygit.nix
    ./project.nix
    ./flash.nix
    ./colorizer.nix
    ./treesitter-textobjects.nix
    ./comment.nix
    ./surround.nix
    ./tabout.nix
    ./terminal.nix
  ];
}
